<?php

declare(strict_types=1);

namespace App\Services\AI;

use RuntimeException;

/**
 * Replaces every `$ref:<pending_action_id>` in an action payload with the real database ID
 * generated by the earlier step.
 *
 * Runs inside the approving database transaction. A reference whose step has not
 * been resolved or executed is an error, preventing orphaned or disconnected writes.
 */
final readonly class PlanReferenceResolver
{
    /**
     * Resolve all references in $data using a map of actionId => createdResultData.
     *
     * @param  array<array-key, mixed>  $data
     * @param  array<string, array<string, mixed>>  $executedActionResults  e.g. ['action_1' => ['id' => 123]]
     * @return array<array-key, mixed>
     */
    public function resolve(array $data, array $executedActionResults): array
    {
        if (PlanReference::targetsIn($data) === []) {
            return $data;
        }

        return PlanReference::rewrite($data, function (string $target) use ($executedActionResults): string {
            $actionId = PlanReference::actionId($target);
            $index = PlanReference::index($target);

            if (! isset($executedActionResults[$actionId])) {
                throw new RuntimeException(
                    sprintf('Dependent action "%s" has not been executed yet. Cannot resolve reference.', $actionId)
                );
            }

            $result = $executedActionResults[$actionId];

            if ($index === null) {
                $resolvedId = $result['id'] ?? null;
            } else {
                $items = is_array($result['items'] ?? null) ? $result['items'] : [];
                $resolvedId = $items[$index]['id'] ?? null;
            }

            if ($resolvedId === null) {
                throw new RuntimeException(
                    sprintf('Could not resolve generated record ID for action "%s".', $target)
                );
            }

            return (string) $resolvedId;
        });
    }
}
